version: 2
updates:
  - directory: /
    package-ecosystem: "npm"
    schedule:
      interval: "monthly"
      time: "04:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - directory: /client
    package-ecosystem: "npm"
    schedule:
      interval: "monthly"
      time: "04:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
