name: Client - lint & type check

on: [push, pull_request]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20, 22]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.nodejs }}
      - name: Install dependencies
        run: npm install
        working-directory: client
      - name: Lint
        run: npm run lint
        working-directory: client
      - name: Format
        run: npm run format:check
        working-directory: client
      - name: TypeCheck
        run: npm run type-check
        working-directory: client
