name: Client - lint & type check

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up environment
        uses: actions/setup-node@v4.3.0
      - name: Install dependencies
        run: npm install
        working-directory: client
      - name: Lint
        run: npm run lint
        working-directory: client
      - name: Format
        run: npm run format:check
        working-directory: client
      - name: TypeCheck
        run: npm run type-check
        working-directory: client
